### ISSUE TITLE
No SavedGameData  When I reinstall app and call  GKFetchSavedGames 。

### ISSUE THREAD

**Issue by chenhuo2** [dark-1-games/GKNativeExtensions#2]
I used your plugin
It looks good that I can successfully save and read my game data.
But after I delete my game and reinstall the game. It shows that the length of the array is 0  when I call GKFetchSavedGames, which cause the function cannot work successfully.

**Comment by FREEZX** [comment]
Hi,
Is your iCloud container correctly setup?
Make sure your game set to sync to icloud in your iOS settings.

I'll try to reproduce your issue in the next couple of days, but so far, i was able to fetch, save and load games correctly while the app was simultaneously running on two different phones. All issues i have encountered were usually due to bad configuration, either of the xcode project or the device settings.

**Comment by chenhuo2** [comment]
Hi,
I can successfully read my data after reinstalling the app in one phone.
However, when I did the same thing in other different phones, an issue appears that the length of the array is 0 when I call GKFetchSavedGames, which cause the function cannot work successfully.

**Comment by FREEZX** [comment]
If the issue appears on different phones, make sure they are logged in on the same iCloud and game center accounts (iCloud is super important), and obviously that both phones have a functional internet connection (Wasted hours with this mistake myself a couple of times :P).

**Comment by chenhuo2** [comment]
Hi, 
Sorry about my poor English. You might misunderstand my issue. I am trying to test this feature in a new device. This means that I am using a new device with a new account to test uploading and recovering the game data which belongs to the new account. I am not trying to recovery the data to different accounts. 
Thanks for your patience.

**Comment by FREEZX** [comment]
Hi @chenhuo2 
I did try to reproduce the issue on two devices, but i was able to read and write data simultaneously on both devices. Getting the list of saves returned the correct saves on both devices.

At this point, i think you should maybe look at the iCloud container configuration of your app.
Make sure you have a cloud container linked to your app here: https://developer.apple.com/account/ios/identifier/cloudContainer
and that you have iCloud enabled for your app id here:
https://developer.apple.com/account/ios/identifier/bundle
Besides these, the correct icloud container should be set up in your XCode project.

**Comment by FREEZX** [comment]
Closing stale issue. Comment if you still encounter this.

**Comment by DunkUK** [comment]
I'm having the same issue.  The list of save games will return 0 games, but ONLY on *first* launch after a complete uninstall->reinstall of the app.  If you avoid saving, but reboot the app, the cloud load will complete successfully.  HOWEVER, if you try to cloud-save during the *first* launch (after the return 0 failure), then the cloud save will be overwritten - not even allowing a subsequent run to see 2 saves (so cannot attempt a conflict resolve).

My containers are setup correctly as far as I can see.  Normal usage produces 'success' output on saving/loading, as well as visible data in the iOS system's iCloud storage (account->iCloud->Manage storage).
The iCloud setting on my bundleID:
![image](https://user-images.githubusercontent.com/30832665/66494579-ca8e2380-eaaf-11e9-9fde-d32329987312.png)
iCloud container assignment:
![image](https://user-images.githubusercontent.com/30832665/66494921-56a04b00-eab0-11e9-8f4a-923023d02aaa.png)
CloudKit settings screen:
![image](https://user-images.githubusercontent.com/30832665/66494974-7172bf80-eab0-11e9-8aeb-e91c988922c6.png)

**Comment by FREEZX** [comment]
@DunkUK I'm aware of this particular issue, but it seems like it stems from the underlying GKSavedGame library. A known workaround is to wait for some 10s before attempting to load the game (if running for the first time).

References:
https://discuss.cocos2d-x.org/t/loadallgamedata-callback/41750/18
https://forums.developer.apple.com/message/188277

I have submitted a bug report and apparently there's a potential fix in iOS 13.2 Seed 1 (17B5059g) (whatever that means)

**Comment by DunkUK** [comment]
Thanks for the workaround suggestion!
I changed my logic to poll the fetchSavedGames, then if it returns 0 games, wait a second and poll again.  I then continue this until it finds something, or my intro animation is finished (20 seconds or so) - at which point I assume there is no cloud save.  This seems to work well enough to ship.

An alternative would be to *ask* the user if they want to attempt an extended cloud load.  I didn't go with this option since it's a worse experience for first-time players.
