### ISSUE TITLE
Bindings currently require an extra 'CPS_GAME_CENTER' compile flag

### ISSUE THREAD

**Issue by DunkUK** [dark-1-games/GKNativeExtensions#3]
The Unity Bindings GKNativeExtensions.cs contains CPS_GAME_CENTER compilation conditionals, which cause default usage to never call down to the native functions.  Presumably this library is supposed to be packaged as part of a larger solution, since I don't see anything that could set the compile flag.
Removing the CPS_GAME_CENTER flags makes the functions call through.

**Comment by FREEZX** [comment]
You're correct, i should remove those. :)

**Comment by FREEZX** [comment]
Fixed with PR https://github.com/dark-1-games/GKNativeExtensions/pull/4
